{
  parserClass="intellij_awk.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="intellij_awk.psi"
  psiImplPackage="intellij_awk.psi.impl"

  elementTypeHolderClass="intellij_awk.psi.SimpleTypes"
  elementTypeClass="intellij_awk.psi.SimpleElementType"
  tokenTypeClass="intellij_awk.psi.SimpleTokenType"

  psiImplUtilClass="intellij_awk.psi.impl.SimplePsiImplUtil"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
  pin=3
  recoverWhile="recover_property"
  mixin="intellij_awk.psi.impl.SimpleNamedElementImpl"
  implements="intellij_awk.psi.SimpleNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}
private recover_property ::= !(KEY|SEPARATOR|COMMENT)
